/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from '../../src/toast.module';
import * as import2 from '@angular/common';
import * as import3 from './toast-container.component.ngfactory';
class ToastModuleInjector extends import0.ɵNgModuleInjector<import1.ToastModule> {
  _CommonModule_0:import2.CommonModule;
  _ToastModule_1:import1.ToastModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,[import3.ToastContainerNgFactory],([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.ToastModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ToastModule_1 = new import1.ToastModule();
    return this._ToastModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.ToastModule)) { return this._ToastModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ToastModuleNgFactory:import0.NgModuleFactory<import1.ToastModule> = new import0.NgModuleFactory<any>(ToastModuleInjector,import1.ToastModule);