/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './toast-container.component';
import * as import1 from '@angular/core';
import * as import2 from '../node_modules/@angular/common/index.ngfactory';
import * as import3 from '@angular/common';
import * as import4 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import5 from './toast-options';
export class Wrapper_ToastContainer {
  /*private*/ _eventHandler:Function;
  context:import0.ToastContainer;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.ToastContainer(p0,p1,p2);
  }
  ngOnDetach(view:import1.ɵAppView<any>,componentView:import1.ɵAppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.ɵAppView<any>,el:any):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.ɵAppView<any>,componentView:import1.ɵAppView<any>,el:any):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.ɵAppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
const styles_ToastContainer:any[] = ([] as any[]);
var ToastContainer_inOut_states:any = {
  'flyRight': {
    'opacity': '1',
    'transform': 'translateX(0)'
  }
  ,
  'flyLeft': {
    'opacity': '1',
    'transform': 'translateX(0)'
  }
  ,
  'fade': {'opacity': '1'},
  'slideDown': {
    'opacity': '1',
    'transform': 'translateY(0)'
  }
  ,
  'slideUp': {
    'opacity': '1',
    'transform': 'translateY(0)'
  }
  ,
  '*': {},
  'void': {}
}
;
function ToastContainer_inOut_factory(view:import1.ɵAppView<any>,element:any,currentState:any,nextState:any):import1.ɵAnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'inOut'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = ToastContainer_inOut_states['*'];
  var startStateStyles:any = ToastContainer_inOut_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = ToastContainer_inOut_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'void') && (nextState == 'flyRight')))) {
      player = new import1.ɵAnimationSequencePlayer([view.renderer.animate(element,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {
          'opacity': '0',
          'transform': 'translateX(100%)'
        }

      ]
      )),import1.ɵbalanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import1.ɵAnimationKeyframe(0,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{}]))),
        new import1.ɵAnimationKeyframe(1,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),200,0,'ease-in',previousPlayers)]);
    totalTime = 200;
  }
  if (((player == (null as any)) && ((currentState == 'flyRight') && (nextState == 'void')))) {
      player = new import1.ɵAnimationSequencePlayer([view.renderer.animate(element,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[startStateStyles])),[
          new import1.ɵAnimationKeyframe(0,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{
            'opacity': 'true',
            'transform': 'true'
          }
        ]))),
          new import1.ɵAnimationKeyframe(1,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{
            'opacity': '0',
            'transform': 'translateX(100%)'
          }
        ])))
      ]
    ,200,0,(null as any),previousPlayers)]);
    totalTime = 200;
  }
  if (((player == (null as any)) && ((currentState == 'void') && (nextState == 'flyLeft')))) {
      player = new import1.ɵAnimationSequencePlayer([view.renderer.animate(element,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {
          'opacity': '0',
          'transform': 'translateX(-100%)'
        }

      ]
      )),import1.ɵbalanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import1.ɵAnimationKeyframe(0,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{}]))),
        new import1.ɵAnimationKeyframe(1,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),200,0,'ease-in',previousPlayers)]);
    totalTime = 200;
  }
  if (((player == (null as any)) && ((currentState == 'flyLeft') && (nextState == 'void')))) {
      player = new import1.ɵAnimationSequencePlayer([view.renderer.animate(element,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[startStateStyles])),[
          new import1.ɵAnimationKeyframe(0,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{
            'opacity': 'true',
            'transform': 'true'
          }
        ]))),
          new import1.ɵAnimationKeyframe(1,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{
            'opacity': '0',
            'transform': 'translateX(-100%)'
          }
        ])))
      ]
    ,200,0,(null as any),previousPlayers)]);
    totalTime = 200;
  }
  if (((player == (null as any)) && ((currentState == 'void') && (nextState == 'fade')))) {
      player = new import1.ɵAnimationSequencePlayer([view.renderer.animate(element,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {'opacity': '0'}
      ]
      )),import1.ɵbalanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import1.ɵAnimationKeyframe(0,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{}]))),
        new import1.ɵAnimationKeyframe(1,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),300,0,'ease-in',previousPlayers)]);
    totalTime = 300;
  }
  if (((player == (null as any)) && ((currentState == 'fade') && (nextState == 'void')))) {
      player = new import1.ɵAnimationSequencePlayer([view.renderer.animate(element,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[startStateStyles])),[
        new import1.ɵAnimationKeyframe(0,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{'opacity': 'true'}]))),
        new import1.ɵAnimationKeyframe(1,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{'opacity': '0'}])))
      ]
    ,300,0,(null as any),previousPlayers)]);
    totalTime = 300;
  }
  if (((player == (null as any)) && ((currentState == 'void') && (nextState == 'slideDown')))) {
      player = new import1.ɵAnimationSequencePlayer([view.renderer.animate(element,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {
          'opacity': '0',
          'transform': 'translateY(-200%)'
        }

      ]
      )),import1.ɵbalanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import1.ɵAnimationKeyframe(0,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{}]))),
        new import1.ɵAnimationKeyframe(1,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),300,0,'ease-in',previousPlayers)]);
    totalTime = 300;
  }
  if (((player == (null as any)) && ((currentState == 'slideDown') && (nextState == 'void')))) {
      player = new import1.ɵAnimationSequencePlayer([view.renderer.animate(element,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[startStateStyles])),[
          new import1.ɵAnimationKeyframe(0,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{
            'opacity': 'true',
            'transform': 'true'
          }
        ]))),
          new import1.ɵAnimationKeyframe(1,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{
            'opacity': '0',
            'transform': 'translateY(-200%)'
          }
        ])))
      ]
    ,300,0,(null as any),previousPlayers)]);
    totalTime = 300;
  }
  if (((player == (null as any)) && ((currentState == 'void') && (nextState == 'slideUp')))) {
      player = new import1.ɵAnimationSequencePlayer([view.renderer.animate(element,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[
        startStateStyles,
        {
          'opacity': '0',
          'transform': 'translateY(200%)'
        }

      ]
      )),import1.ɵbalanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import1.ɵAnimationKeyframe(0,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{}]))),
        new import1.ɵAnimationKeyframe(1,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),300,0,'ease-in',previousPlayers)]);
    totalTime = 300;
  }
  if (((player == (null as any)) && ((currentState == 'slideUp') && (nextState == 'void')))) {
      player = new import1.ɵAnimationSequencePlayer([view.renderer.animate(element,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[startStateStyles])),[
          new import1.ɵAnimationKeyframe(0,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{
            'opacity': 'true',
            'transform': 'true'
          }
        ]))),
          new import1.ɵAnimationKeyframe(1,new import1.ɵAnimationStyles(import1.ɵcollectAndResolveStyles(collectedStyles,[{
            'opacity': '0',
            'transform': 'translateY(200%)'
          }
        ])))
      ]
    ,300,0,(null as any),previousPlayers)]);
    totalTime = 300;
  }
  if ((player == (null as any))) { (player = new import1.ɵNoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import1.ɵrenderStyles(element,view.renderer,import1.ɵprepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import1.ɵAnimationSequencePlayer(previousPlayers).destroy();
  import1.ɵrenderStyles(element,view.renderer,import1.ɵclearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'inOut',player);
  return new import1.ɵAnimationTransition(player,element,'inOut',currentState,nextState,totalTime);
}
class View_ToastContainer_2 extends import1.ɵAppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import1.ɵview_utils.ViewUtils,parentView:import1.ɵAppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import1.ɵViewContainer) {
    super(View_ToastContainer_2,RenderType_ToastContainer,import1.ɵViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ɵChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import1.ComponentRef<any> {
    this._el_0 = import1.ɵview_utils.createRenderElement(this.renderer,(null as any),'div',new import1.ɵview_utils.InlineArray2(2,'class','toast-close-button'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'×\n        ',(null as any));
    var disposable_0:Function = import1.ɵview_utils.subscribeToRenderElement(this,this._el_0,new import1.ɵview_utils.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.parentView.context.removeToast(this.parentView.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_ToastContainer_3 extends import1.ɵAppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import1.ɵview_utils.ViewUtils,parentView:import1.ɵAppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import1.ɵViewContainer) {
    super(View_ToastContainer_3,RenderType_ToastContainer,import1.ɵViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ɵChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = (undefined as any);
    this._expr_3 = (undefined as any);
  }
  createInternal(rootSelector:string):import1.ComponentRef<any> {
    this._el_0 = import1.ɵview_utils.createRenderElement(this.renderer,(null as any),'div',import1.ɵview_utils.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal():void {
    const currVal_2:any = import1.ɵview_utils.inlineInterpolate(1,'',(this.parentView.context.$implicit.config.titleClass || this.parentView.parentView.context.titleClass),'');
    import1.ɵview_utils.checkRenderProperty(this,this._el_0,'className',this._expr_2,(this._expr_2 = currVal_2),false,(null as any));
    const currVal_3:any = import1.ɵview_utils.inlineInterpolate(1,'',this.parentView.context.$implicit.title,'');
    import1.ɵview_utils.checkRenderText(this,this._text_1,this._expr_3,(this._expr_3 = currVal_3),false);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ToastContainer_4 extends import1.ɵAppView<any> {
  _el_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import1.ɵview_utils.ViewUtils,parentView:import1.ɵAppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import1.ɵViewContainer) {
    super(View_ToastContainer_4,RenderType_ToastContainer,import1.ɵViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ɵChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_1 = (undefined as any);
  }
  createInternal(rootSelector:string):import1.ComponentRef<any> {
    this._el_0 = import1.ɵview_utils.createRenderElement(this.renderer,(null as any),'span',import1.ɵview_utils.EMPTY_INLINE_ARRAY,(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return (null as any);
  }
  detectChangesInternal():void {
    const currVal_1:any = this.parentView.parentView.context.sanitizer.bypassSecurityTrustHtml(this.parentView.context.$implicit.message);
    import1.ɵview_utils.checkRenderProperty(this,this._el_0,'innerHTML',this._expr_1,(this._expr_1 = currVal_1),false,import1.SecurityContext.HTML);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ToastContainer_5 extends import1.ɵAppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import1.ɵview_utils.ViewUtils,parentView:import1.ɵAppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import1.ɵViewContainer) {
    super(View_ToastContainer_5,RenderType_ToastContainer,import1.ɵViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ɵChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = (undefined as any);
    this._expr_3 = (undefined as any);
  }
  createInternal(rootSelector:string):import1.ComponentRef<any> {
    this._el_0 = import1.ɵview_utils.createRenderElement(this.renderer,(null as any),'span',import1.ɵview_utils.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  detectChangesInternal():void {
    const currVal_2:any = import1.ɵview_utils.inlineInterpolate(1,'',(this.parentView.context.$implicit.config.messageClass || this.parentView.parentView.context.messageClass),'');
    import1.ɵview_utils.checkRenderProperty(this,this._el_0,'className',this._expr_2,(this._expr_2 = currVal_2),false,(null as any));
    const currVal_3:any = import1.ɵview_utils.inlineInterpolate(1,'',this.parentView.context.$implicit.message,'');
    import1.ɵview_utils.checkRenderText(this,this._text_1,this._expr_3,(this._expr_3 = currVal_3),false);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_ToastContainer_1 extends import1.ɵAppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _vc_2:import1.ɵViewContainer;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import2.Wrapper_NgIf;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _vc_4:import1.ɵViewContainer;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import2.Wrapper_NgIf;
  _text_5:any;
  _el_6:any;
  _NgSwitch_6_3:import2.Wrapper_NgSwitch;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _vc_8:import1.ɵViewContainer;
  _TemplateRef_8_5:any;
  _NgSwitchCase_8_6:import2.Wrapper_NgSwitchCase;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _vc_10:import1.ɵViewContainer;
  _TemplateRef_10_5:any;
  _NgSwitchDefault_10_6:import2.Wrapper_NgSwitchDefault;
  _text_11:any;
  _text_12:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  constructor(viewUtils:import1.ɵview_utils.ViewUtils,parentView:import1.ɵAppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import1.ɵViewContainer) {
    super(View_ToastContainer_1,RenderType_ToastContainer,import1.ɵViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import1.ɵChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_26 = (undefined as any);
    this._expr_27 = (undefined as any);
  }
  createInternal(rootSelector:string):import1.ComponentRef<any> {
    this._el_0 = import1.ɵview_utils.createRenderElement(this.renderer,(null as any),'div',import1.ɵview_utils.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_2 = new import1.ɵViewContainer(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import1.ɵTemplateRef_<any>(this,2,this._anchor_2);
    this._NgIf_2_6 = new import2.Wrapper_NgIf(this._vc_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(this._el_0,' \n        ',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._vc_4 = new import1.ɵViewContainer(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import1.ɵTemplateRef_<any>(this,4,this._anchor_4);
    this._NgIf_4_6 = new import2.Wrapper_NgIf(this._vc_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_6 = import1.ɵview_utils.createRenderElement(this.renderer,this._el_0,'div',import1.ɵview_utils.EMPTY_INLINE_ARRAY,(null as any));
    this._NgSwitch_6_3 = new import2.Wrapper_NgSwitch();
    this._text_7 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_8 = new import1.ɵViewContainer(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import1.ɵTemplateRef_<any>(this,8,this._anchor_8);
    this._NgSwitchCase_8_6 = new import2.Wrapper_NgSwitchCase(this._vc_8.vcRef,this._TemplateRef_8_5,this._NgSwitch_6_3.context);
    this._text_9 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._vc_10 = new import1.ɵViewContainer(10,6,this,this._anchor_10);
    this._TemplateRef_10_5 = new import1.ɵTemplateRef_<any>(this,10,this._anchor_10);
    this._NgSwitchDefault_10_6 = new import2.Wrapper_NgSwitchDefault(this._vc_10.vcRef,this._TemplateRef_10_5,this._NgSwitch_6_3.context);
    this._text_11 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'             \n      ',(null as any));
    var disposable_0:Function = import1.ɵview_utils.subscribeToRenderElement(this,this._el_0,new import1.ɵview_utils.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._text_12
    ]
    ),[disposable_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import3.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import1.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import3.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import1.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import3.NgSwitchCase) && (8 === requestNodeIndex))) { return this._NgSwitchCase_8_6.context; }
    if (((token === import1.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import3.NgSwitchDefault) && (10 === requestNodeIndex))) { return this._NgSwitchDefault_10_6.context; }
    if (((token === import3.NgSwitch) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._NgSwitch_6_3.context; }
    return notFoundResult;
  }
  detectChangesInternal():void {
    const currVal_26:any = this.parentView.context.animate;
    if (import1.ɵview_utils.checkBinding(this,this._expr_26,currVal_26,false)) {
      var animationTransition_inOut:any = this.componentType.animations['inOut'](this,this._el_0,(!this.numberOfChecks? 'void': this._expr_26),currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_2_0_0:any = this.context.$implicit.config.showCloseButton;
    this._NgIf_2_6.check_ngIf(this,currVal_2_0_0,false);
    this._NgIf_2_6.ngDoCheck(this,this._anchor_2);
    const currVal_4_0_0:any = this.context.$implicit.title;
    this._NgIf_4_6.check_ngIf(this,currVal_4_0_0,false);
    this._NgIf_4_6.ngDoCheck(this,this._anchor_4);
    const currVal_6_0_0:any = this.context.$implicit.config.enableHTML;
    this._NgSwitch_6_3.check_ngSwitch(this,currVal_6_0_0,false);
    this._NgSwitch_6_3.ngDoCheck(this,this._el_6);
    const currVal_8_0_0:any = true;
    this._NgSwitchCase_8_6.check_ngSwitchCase(this,currVal_8_0_0,false);
    this._NgSwitchCase_8_6.ngDoCheck(this,this._anchor_8);
    this._NgSwitchDefault_10_6.ngDoCheck(this,this._anchor_10);
    this._vc_2.detectChangesInNestedViews(this.throwOnChange);
    this._vc_4.detectChangesInNestedViews(this.throwOnChange);
    this._vc_8.detectChangesInNestedViews(this.throwOnChange);
    this._vc_10.detectChangesInNestedViews(this.throwOnChange);
    const currVal_27:any = import1.ɵview_utils.inlineInterpolate(1,'toast toast-',this.context.$implicit.type,'');
    import1.ɵview_utils.checkRenderProperty(this,this._el_0,'className',this._expr_27,(this._expr_27 = currVal_27),false,(null as any));
  }
  destroyInternal():void {
    this._vc_2.destroyNestedViews();
    this._vc_4.destroyNestedViews();
    this._vc_8.destroyNestedViews();
    this._vc_10.destroyNestedViews();
  }
  detachInternal():void {
    const currVal_26:any = this.parentView.context.animate;
    var animationTransition_inOut:any = this.componentType.animations['inOut'](this,this._el_0,currVal_26,'void');
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.ɵAppView<any> {
    if ((nodeIndex == 2)) { return new View_ToastContainer_2(this.viewUtils,this,2,this._anchor_2,this._vc_2); }
    if ((nodeIndex == 4)) { return new View_ToastContainer_3(this.viewUtils,this,4,this._anchor_4,this._vc_4); }
    if ((nodeIndex == 8)) { return new View_ToastContainer_4(this.viewUtils,this,8,this._anchor_8,this._vc_8); }
    if ((nodeIndex == 10)) { return new View_ToastContainer_5(this.viewUtils,this,10,this._anchor_10,this._vc_10); }
    return (null as any);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.clicked(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
export var RenderType_ToastContainer:import1.RenderComponentType = import1.ɵview_utils.createRenderComponentType('',0,import1.ViewEncapsulation.None,styles_ToastContainer,{'inOut': ToastContainer_inOut_factory});
export class View_ToastContainer_0 extends import1.ɵAppView<import0.ToastContainer> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _vc_3:import1.ɵViewContainer;
  _TemplateRef_3_5:any;
  _NgForOf_3_6:import2.Wrapper_NgForOf;
  __NgFor_3_7:any;
  _text_4:any;
  _text_5:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import1.ɵview_utils.ViewUtils,parentView:import1.ɵAppView<any>,parentIndex:number,parentElement:any) {
    super(View_ToastContainer_0,RenderType_ToastContainer,import1.ɵViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import1.ɵChangeDetectorStatus.CheckAlways);
    this._expr_10 = (undefined as any);
    this._expr_11 = (undefined as any);
  }
  get _NgFor_3_7():any {
    if ((this.__NgFor_3_7 == null)) { (this.__NgFor_3_7 = this._NgForOf_3_6.context); }
    return this.__NgFor_3_7;
  }
  createInternal(rootSelector:string):import1.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import1.ɵview_utils.createRenderElement(this.renderer,parentRenderNode,'div',new import1.ɵview_utils.InlineArray2(2,'id','toast-container'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._vc_3 = new import1.ɵViewContainer(3,1,this,this._anchor_3);
    this._TemplateRef_3_5 = new import1.ɵTemplateRef_<any>(this,3,this._anchor_3);
    this._NgForOf_3_6 = new import2.Wrapper_NgForOf(this._vc_3.vcRef,this._TemplateRef_3_5,this.parentView.injectorGet(import1.IterableDiffers,this.parentIndex));
    this._text_4 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._text_5
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import3.NgForOf) && (3 === requestNodeIndex))) { return this._NgForOf_3_6.context; }
    if (((token === import3.NgFor) && (3 === requestNodeIndex))) { return this._NgFor_3_7; }
    return notFoundResult;
  }
  detectChangesInternal():void {
    const currVal_3_0_0:any = this.context.toasts;
    this._NgForOf_3_6.check_ngForOf(this,currVal_3_0_0,false);
    this._NgForOf_3_6.ngDoCheck(this,this._anchor_3);
    this._vc_3.detectChangesInNestedViews(this.throwOnChange);
    const currVal_10:any = this.context.position;
    import1.ɵview_utils.checkRenderStyle(this,this._el_1,'position',(null as any),this._expr_10,(this._expr_10 = currVal_10),false,import1.SecurityContext.STYLE);
    const currVal_11:any = import1.ɵview_utils.inlineInterpolate(1,'',this.context.positionClass,'');
    import1.ɵview_utils.checkRenderProperty(this,this._el_1,'className',this._expr_11,(this._expr_11 = currVal_11),false,(null as any));
  }
  destroyInternal():void {
    this._vc_3.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.ɵAppView<any> {
    if ((nodeIndex == 3)) { return new View_ToastContainer_1(this.viewUtils,this,3,this._anchor_3,this._vc_3); }
    return (null as any);
  }
}
var RenderType_ToastContainer_Host:import1.RenderComponentType = import1.ɵview_utils.createRenderComponentType('',0,import1.ViewEncapsulation.None,([] as any[]),{});
class View_ToastContainer_Host_0 extends import1.ɵAppView<any> {
  _el_0:any;
  compView_0:import1.ɵAppView<import0.ToastContainer>;
  _ToastContainer_0_3:Wrapper_ToastContainer;
  constructor(viewUtils:import1.ɵview_utils.ViewUtils,parentView:import1.ɵAppView<any>,parentIndex:number,parentElement:any) {
    super(View_ToastContainer_Host_0,RenderType_ToastContainer_Host,import1.ɵViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import1.ɵChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import1.ComponentRef<any> {
    this._el_0 = import1.ɵview_utils.selectOrCreateRenderHostElement(this.renderer,'toast-container',import1.ɵview_utils.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_ToastContainer_0(this.viewUtils,this,0,this._el_0);
    this._ToastContainer_0_3 = new Wrapper_ToastContainer(this.injectorGet(import4.DomSanitizer,this.parentIndex),this.compView_0.ref,this.injectorGet(import5.ToastOptions,this.parentIndex,(null as any)));
    this.compView_0.create(this._ToastContainer_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import1.ɵComponentRef_<any>(0,this,this._el_0,this._ToastContainer_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ToastContainer) && (0 === requestNodeIndex))) { return this._ToastContainer_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal():void {
    this._ToastContainer_0_3.ngDoCheck(this,this._el_0);
    this.compView_0.internalDetectChanges(this.throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const ToastContainerNgFactory:import1.ComponentFactory<import0.ToastContainer> = new import1.ComponentFactory<import0.ToastContainer>('toast-container',View_ToastContainer_Host_0,import0.ToastContainer);